/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/filter/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate filter syntax. */
        get: operations["validate_filter_get_filter_validation_get"];
        put?: never;
        /** Validate filter syntax. */
        post: operations["validate_filter_post_filter_validation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata of the underlying database. */
        get: operations["get_metadata_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/features/{measure}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aggregate features by {measure} as time series.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. You can not derive statistics for all other relations.
         */
        post: operations["post_features_as_json_stats_features__measure__json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/features/{measure}.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aggregate features by {measure} as time series.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_features_as_csv_stats_features__measure__csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/contributors/activity.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Active contributors per time bin. */
        post: operations["post_contributors_activity_as_json_stats_contributors_activity_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/contributors/activity.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Active contributors per time bin.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_contributors_activity_as_csv_stats_contributors_activity_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/currentness/{measure}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Currentness of features in time bins. */
        post: operations["post_currentness_as_json_stats_currentness__measure__json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/currentness/{measure}.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Currentness of features in time bins.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_currentness_as_csv_stats_currentness__measure__csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/features.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download features.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        get: operations["get_contributions_extract_extraction_features_parquet_get"];
        put?: never;
        /**
         * Download features.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        post: operations["post_contributions_extract_extraction_features_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/features.arrow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download features.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        get: operations["get_contributions_extract_arrow_extraction_features_arrow_get"];
        put?: never;
        /**
         * Download features.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        post: operations["post_contributions_extract_arrow_extraction_features_arrow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/collections.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download collections.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) as geometry collections. For each relation a separate row is returned for their linear, polygonal or point members
         */
        get: operations["get_features_collections_extract_extraction_collections_parquet_get"];
        put?: never;
        /**
         * Download collections.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) as geometry collections. For each relation a separate row is returned for their linear, polygonal or point members
         */
        post: operations["post_features_collections_extract_extraction_collections_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/collections_members.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download collections members.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) members.For each relation all members features are returned row by row.
         */
        get: operations["get_features_collections_members_extract_extraction_collections_members_parquet_get"];
        put?: never;
        /**
         * Download collections members.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) members.For each relation all members features are returned row by row.
         */
        post: operations["post_features_collections_members_extract_extraction_collections_members_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check health. */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Attribution */
        Attribution: {
            /**
             * Url
             * @default https://ohsome.org/copyrights
             */
            url: string;
            /**
             * Text
             * @default © OpenStreetMap contributors
             */
            text: string;
        };
        /** CollectionsExtractionRequestParametersModel */
        CollectionsExtractionRequestParametersModel: {
            /**
             * Clip
             * @description Whether to clip extracted features with AOI or not.
             * @default true
             */
            clip: boolean;
            /**
             * Timestamp
             * @description Extraction timestamp (ISO-8601, UTC). For the most recent data 'latest' can be used instead of a timestamp.
             * @default latest
             * @example latest
             * @example 2026-04-17T00:00:00Z
             */
            timestamp: string | "latest";
            /**
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter)
             * @example type:relation and type=route and route=bus and service=night
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or WKT. As geometry only Polygon or MultiPolygon are allowed.
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
        };
        /** ExtractionRequestParametersModel */
        ExtractionRequestParametersModel: {
            /**
             * Clip
             * @description Whether to clip extracted features with AOI or not.
             * @default true
             */
            clip: boolean;
            /**
             * Timestamp
             * @description Extraction timestamp (ISO-8601, UTC). For the most recent data 'latest' can be used instead of a timestamp.
             * @default latest
             * @example latest
             * @example 2026-04-17T00:00:00Z
             */
            timestamp: string | "latest";
            /**
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter)
             * @example type:node and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or WKT. As geometry only Polygon or MultiPolygon are allowed.
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
        };
        /** FilterRequestModel */
        FilterRequestModel: {
            /**
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter)
             * @example type:node and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
        };
        /** FilterResponseModel */
        FilterResponseModel: {
            /**
             * Apiversion
             * @default 2.0.0a5+31c22be
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            filter: components["schemas"]["OhsomeFilter"];
        };
        /** GroupByTagModel */
        GroupByTagModel: {
            /**
             * Type
             * @constant
             */
            type: "byTag";
            /** Key */
            key: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /**
             * Status
             * @default Ok
             */
            status: string;
        };
        /**
         * MeasureRequestModel
         * @enum {string}
         */
        MeasureRequestModel: "count" | "length" | "area";
        /** Metadata */
        Metadata: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** MetadataResponseModel */
        MetadataResponseModel: {
            /**
             * Apiversion
             * @default 2.0.0a5+31c22be
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            temporalExtent: components["schemas"]["Metadata"];
        };
        /**
         * MultiPolygon
         * @description MultiPolygon Model
         */
        MultiPolygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][][];
        };
        OhsomeFilter: string;
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /** SnapshotColumnsGrouped */
        SnapshotColumnsGrouped: {
            /** Timestamp */
            timestamp: string[];
            /** Value */
            value: number[];
            /**
             * Values
             * @example null
             */
            values?: {
                [key: string]: number[];
            } | null;
        };
        /** SnapshotColumnsResponseModel */
        SnapshotColumnsResponseModel: {
            /**
             * Apiversion
             * @default 2.0.0a5+31c22be
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            result: components["schemas"]["SnapshotColumnsGrouped"];
        };
        /** SnapshotRow */
        SnapshotRow: {
            /** Value */
            value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SnapshotRowGroupedByTag */
        SnapshotRowGroupedByTag: {
            /** Value */
            value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tagvalue */
            tagvalue: string;
        };
        /** SnapshotsResponseModel */
        SnapshotsResponseModel: {
            /**
             * Apiversion
             * @default 2.0.0a5+31c22be
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            /** Result */
            result: (components["schemas"]["SnapshotRow"] | components["schemas"]["SnapshotRowGroupedByTag"])[];
        };
        /** TimeBinColumns */
        TimeBinColumns: {
            /** Start */
            start: string[];
            /** End */
            end: string[];
            /** Value */
            value: number[];
        };
        /** TimeBinRow */
        TimeBinRow: {
            /** Value */
            value: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** TimeBinSizeRequestModel */
        TimeBinSizeRequestModel: {
            /**
             * Start
             * @description Start timestamp (ISO-8601, UTC). Earliest timestamp is 2007-10-08T00:00:00Z. As shorthand 'earliest' can be used instead of a timestamp.
             * @example 2026-01-01T00:00:00Z
             * @example earliest
             */
            start: string | "earliest";
            /**
             * End
             * @description End timestamp (ISO-8601, UTC). To include the most recent data 'latest' can be used instead of a timestamp.
             * @example 2026-04-17T00:00:00Z
             */
            end: string | "latest";
            /**
             * Binsize
             * @description Bin size (ISO-8601 duration).
             * @example P1M
             */
            binSize?: string | null;
        };
        /** TimeBinsColumnsResponseModel */
        TimeBinsColumnsResponseModel: {
            /**
             * Apiversion
             * @default 2.0.0a5+31c22be
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            result: components["schemas"]["TimeBinColumns"];
        };
        /** TimeBinsRequestParametersModel */
        TimeBinsRequestParametersModel: {
            /** @description Time bins defined using a start/end timestamp (ISO-8601, UTC) and a bin size (ISO-8601 duration). Last bin might not cover bin size. Please take a look at the [documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#time). */
            timeBins: components["schemas"]["TimeBinSizeRequestModel"];
            /**
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter)
             * @example type:node and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or WKT. As geometry only Polygon or MultiPolygon are allowed.
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
        };
        /** TimeBinsResponseModel */
        TimeBinsResponseModel: {
            /**
             * Apiversion
             * @default 2.0.0a5+31c22be
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            /** Result */
            result: components["schemas"]["TimeBinRow"][];
        };
        /** TimeIntervalRequestModel */
        TimeIntervalRequestModel: {
            /**
             * Start
             * @description Start timestamp (ISO-8601, UTC). Earliest timestamp is 2007-10-08T00:00:00Z. As shorthand 'earliest' can be used instead of a timestamp.
             * @example 2026-01-01T00:00:00Z
             * @example earliest
             */
            start: string | "earliest";
            /**
             * End
             * @description End timestamp (ISO-8601, UTC). To include the most recent data 'latest' can be used instead of a timestamp.
             * @example 2026-04-17T00:00:00Z
             */
            end: string | "latest";
            /**
             * Interval
             * @description Interval (ISO-8601 duration).
             * @example P1M
             */
            interval?: string | null;
        };
        /** TimeSeriesRequestParametersModel */
        TimeSeriesRequestParametersModel: {
            /**
             * @description (experimental, optional), if given indicates that the results should also values for individual subsets of the result defined by the presence of tags with the given key
             * @example null
             */
            groupBy?: components["schemas"]["GroupByTagModel"] | null;
            /** @description Time series defined using a start/end timestamp (ISO-8601, UTC) and a interval (ISO-8601 duration). The interval between the last two timestamp might not fit given duration. Please take a look at the [documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#time). */
            timeSeries: components["schemas"]["TimeIntervalRequestModel"];
            /**
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter)
             * @example type:node and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or WKT. As geometry only Polygon or MultiPolygon are allowed.
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validate_filter_get_filter_validation_get: {
        parameters: {
            query: {
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter) */
                filter: components["schemas"]["OhsomeFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_filter_post_filter_validation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metadata_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponseModel"];
                };
            };
        };
    };
    post_features_as_json_stats_features__measure__json_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: components["schemas"]["MeasureRequestModel"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeSeriesRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotColumnsResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_features_as_csv_stats_features__measure__csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: components["schemas"]["MeasureRequestModel"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeSeriesRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0a5+31c22be
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     timestamp;result
                     *     2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_contributors_activity_as_json_stats_contributors_activity_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeBinsRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeBinsColumnsResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_contributors_activity_as_csv_stats_contributors_activity_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeBinsRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0a5+31c22be
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     start;end;value
                     *     2007-10-08T00:00:00Z;2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_currentness_as_json_stats_currentness__measure__json_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: components["schemas"]["MeasureRequestModel"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeBinsRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeBinsColumnsResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_currentness_as_csv_stats_currentness__measure__csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: components["schemas"]["MeasureRequestModel"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeBinsRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0a5+31c22be
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     start;end;value
                     *     2007-10-08T00:00:00Z;2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contributions_extract_extraction_features_parquet_get: {
        parameters: {
            query: {
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
                /** @description Extraction timestamp (ISO-8601, UTC). For the most recent data 'latest' can be used instead of a timestamp. */
                timestamp?: string | "latest";
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter) */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description Area of interest as Bounding Box. */
                aoi: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_contributions_extract_extraction_features_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contributions_extract_arrow_extraction_features_arrow_get: {
        parameters: {
            query: {
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
                /** @description Extraction timestamp (ISO-8601, UTC). For the most recent data 'latest' can be used instead of a timestamp. */
                timestamp?: string | "latest";
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter) */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description Area of interest as Bounding Box. */
                aoi: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_contributions_extract_arrow_extraction_features_arrow_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_collections_extract_extraction_collections_parquet_get: {
        parameters: {
            query: {
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
                /** @description Extraction timestamp (ISO-8601, UTC). For the most recent data 'latest' can be used instead of a timestamp. */
                timestamp?: string | "latest";
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter) */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description Area of interest as Bounding Box. */
                aoi: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_features_collections_extract_extraction_collections_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionsExtractionRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_collections_members_extract_extraction_collections_members_parquet_get: {
        parameters: {
            query: {
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
                /** @description Extraction timestamp (ISO-8601, UTC). For the most recent data 'latest' can be used instead of a timestamp. */
                timestamp?: string | "latest";
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter) */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description Area of interest as Bounding Box. */
                aoi: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_features_collections_members_extract_extraction_collections_members_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionsExtractionRequestParametersModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
}
