/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/filter/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate filter syntax. */
        get: operations["validate_filter_get_filter_validation_get"];
        put?: never;
        /** Validate filter syntax. */
        post: operations["validate_filter_post_filter_validation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata of the underlying database. */
        get: operations["get_metadata_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/features/{measure}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aggregate features by {measure} as time series.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. You can not derive statistics for all other relations.
         */
        post: operations["post_features_as_json_stats_features__measure__json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/features/{measure}.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aggregate features by {measure} as time series.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_features_as_csv_stats_features__measure__csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/contributors/count.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Active contributors per time bin. */
        post: operations["post_contributors_count_as_json_stats_contributors_count_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/contributors/count.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Active contributors per time bin.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_contributors_count_as_csv_stats_contributors_count_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/contributions/count.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contributions per time bin. */
        post: operations["post_contributors_count_as_json_stats_contributions_count_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/contributions/count.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Active contributors per time bin.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_contributors_count_as_csv_stats_contributions_count_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/currentness/{measure}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Currentness of features in time bins. */
        post: operations["post_currentness_as_json_stats_currentness__measure__json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/currentness/{measure}.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Currentness of features in time bins.
         * @description CSV Response Format:
         *     - Delimiter: `;`
         *     - Comments: `#`
         *     - Line terminator: `\n`
         *     - Quote character: `\`
         */
        post: operations["post_currentness_as_csv_stats_currentness__measure__csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/features.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download features.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        get: operations["get_features_extract_extraction_features_parquet_get"];
        put?: never;
        /**
         * Download features.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        post: operations["post_features_extract_extraction_features_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/collections.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download collections.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) as geometry collections. For each relation a separate row is returned for their linear, polygonal or point members
         */
        get: operations["get_features_collections_extract_extraction_collections_parquet_get"];
        put?: never;
        /**
         * Download collections.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) as geometry collections. For each relation a separate row is returned for their linear, polygonal or point members
         */
        post: operations["post_features_collections_extract_extraction_collections_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/collections_members.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download collections members.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) members.For each relation all members features are returned row by row.
         */
        get: operations["get_features_collections_members_extract_extraction_collections_members_parquet_get"];
        put?: never;
        /**
         * Download collections members.
         * @description Returns relations (not tagged as `type=multipolygon` or `type=boundary`) members.For each relation all members features are returned row by row.
         */
        post: operations["post_features_collections_members_extract_extraction_collections_members_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/contributions.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download contributions.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        get: operations["get_contributions_extract_extraction_contributions_parquet_get"];
        put?: never;
        /**
         * Download contributions.
         * @description Nodes, ways, and relations tagged as `type=multipolygon` or `type=boundary` are included. Other relations can be queried with the `/extraction/collections.*` endpoints.
         */
        post: operations["post_contributions_extract_extraction_contributions_parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check health. */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Attribution */
        Attribution: {
            /**
             * Url
             * @default https://ohsome.org/copyrights
             */
            url: string;
            /**
             * Text
             * @default © OpenStreetMap contributors
             */
            text: string;
        };
        /** Error */
        Error: {
            /** Type */
            type: string;
            /** Msg */
            msg: string;
        };
        /** ExtractionCollectionsRequest */
        ExtractionCollectionsRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter).
             * @example type:relation and type=route and route=bus and service=night
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            /** Time */
            time: string | "latest";
            /**
             * @description Specific ohsome filter for members.
             * @example geometry:line
             */
            member_filter?: components["schemas"]["OhsomeFilter"] | null;
            /**
             * Clip
             * @description Whether to clip extracted features with AOI or not.
             * @default true
             */
            clip: boolean;
        };
        /** ExtractionContributionsRequest */
        ExtractionContributionsRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            time: components["schemas"]["TimeRange"];
        };
        /** ExtractionFeaturesRequest */
        ExtractionFeaturesRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            /** Time */
            time: string | "latest" | components["schemas"]["TimeRange"];
            /**
             * Clip
             * @description Whether to clip extracted features with AOI or not.
             * @default true
             */
            clip: boolean;
        };
        /** FilterRequest */
        FilterRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
        };
        /** GroupByTag */
        GroupByTag: {
            /**
             * Type
             * @constant
             */
            type: "byTag";
            /** Key */
            key: string;
        };
        /** HTTPError */
        HTTPError: {
            /** Detail */
            detail: components["schemas"]["Error"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default Ok
             */
            status: string;
        };
        /** Metadata */
        Metadata: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** MetadataResponse */
        MetadataResponse: {
            /**
             * Apiversion
             * @default 2.0.0rc2+45857f1
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            temporalExtent: components["schemas"]["Metadata"];
        };
        /**
         * MultiPolygon
         * @description MultiPolygon Model
         */
        MultiPolygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][][];
        };
        OhsomeFilter: string;
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /** StatsContributionsRequest */
        StatsContributionsRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            time: components["schemas"]["TimeBins"];
        };
        /** StatsContributionsResponse */
        StatsContributionsResponse: {
            /**
             * Apiversion
             * @default 2.0.0rc2+45857f1
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            result: components["schemas"]["TimeBinsResult"];
        };
        /** StatsContributorsRequest */
        StatsContributorsRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            time: components["schemas"]["TimeBins"];
        };
        /** StatsContributorsResponse */
        StatsContributorsResponse: {
            /**
             * Apiversion
             * @default 2.0.0rc2+45857f1
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            result: components["schemas"]["TimeBinsResult"];
        };
        /** StatsCurrentnessRequest */
        StatsCurrentnessRequest: {
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            time: components["schemas"]["TimeBins"];
            /**
             * Clip
             * @description If true, length and area calculations use the clipped feature geometries. Clipping can be computationally expensive for large AOIs, depending on your ohsome filter, and is usually unnecessary.
             * @default false
             */
            clip: boolean;
        };
        /** StatsCurrentnessResponse */
        StatsCurrentnessResponse: {
            /**
             * Apiversion
             * @default 2.0.0rc2+45857f1
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            result: components["schemas"]["TimeBinsResult"];
        };
        /** StatsFeaturesRequest */
        StatsFeaturesRequest: {
            /**
             * @description `(experimental, optional)`; If given indicates that the results should also values for individual subsets of the result defined by the presence of tags with the given key
             * @example null
             */
            groupBy?: components["schemas"]["GroupByTag"] | null;
            /**
             * Filter
             * @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html).
             * @example geometry:point and natural=tree
             */
            filter: components["schemas"]["OhsomeFilter"];
            /**
             * Aoi
             * @description Area of interest as a GeoJSON Geometry, Bounding Box or Well Known Text (WGS84, EPSG:4326).
             */
            aoi: [
                number,
                number,
                number,
                number
            ] | (components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"]) | string;
            /** Time */
            time: components["schemas"]["TimeSeries"] | string | "latest";
            /**
             * Clip
             * @description If true, length and area calculations use the clipped feature geometries. Clipping can be computationally expensive for large AOIs, depending on your ohsome filter, and is usually unnecessary.
             * @default false
             */
            clip: boolean;
        };
        /** StatsFeaturesResponse */
        StatsFeaturesResponse: {
            /**
             * Apiversion
             * @default 2.0.0rc2+45857f1
             */
            apiVersion: string;
            /**
             * @default {
             *       "url": "https://ohsome.org/copyrights",
             *       "text": "© OpenStreetMap contributors"
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            /** Result */
            result: components["schemas"]["TimeSeriesResult"] | components["schemas"]["TimeSeriesGroupedByResult"];
        };
        /**
         * TimeBins
         * @description Time bins defined using a start/end timestamp (ISO-8601, UTC) and a bin size (ISO-8601 duration). Last bin might not cover bin size. Please take a look at the [documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#time).
         */
        TimeBins: {
            /**
             * Start
             * @example 2025-01-01T00:00:00Z
             */
            start: string | "earliest";
            /**
             * End
             * @example 2026-01-01T00:00:00Z
             */
            end: string | "latest";
            /**
             * Binsize
             * @description Bin size (ISO-8601 duration).
             * @example P1M
             */
            binSize?: string | null;
        };
        /** TimeBinsResult */
        TimeBinsResult: {
            /** Start */
            start: string[];
            /** End */
            end: string[];
            /** Value */
            value: number[];
        };
        /** TimeRange */
        TimeRange: {
            /**
             * Start
             * @example 2025-01-01T00:00:00Z
             */
            start: string | "earliest";
            /**
             * End
             * @example 2026-01-01T00:00:00Z
             */
            end: string | "latest";
        };
        /**
         * TimeSeries
         * @description Time series defined using a start/end timestamp (ISO-8601, UTC) and a interval (ISO-8601 duration). The interval between the last two timestamp might not fit given duration. Please take a look at the [documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#time).
         */
        TimeSeries: {
            /**
             * Start
             * @example 2025-01-01T00:00:00Z
             */
            start: string | "earliest";
            /**
             * End
             * @example 2026-01-01T00:00:00Z
             */
            end: string | "latest";
            /**
             * Interval
             * @description Interval (ISO-8601 duration).
             * @example P1M
             */
            interval?: string | null;
        };
        /** TimeSeriesGroupedByResult */
        TimeSeriesGroupedByResult: {
            /** Timestamp */
            timestamp: string[];
            /** Value */
            value: number[];
            /** Group */
            group: {
                [key: string]: number[];
            };
        };
        /** TimeSeriesResult */
        TimeSeriesResult: {
            /** Timestamp */
            timestamp: string[];
            /** Value */
            value: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validate_filter_get_filter_validation_get: {
        parameters: {
            query: {
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html). */
                filter: components["schemas"]["OhsomeFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    validate_filter_post_filter_validation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_metadata_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_features_as_json_stats_features__measure__json_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: "count" | "length" | "area";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsFeaturesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsFeaturesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_features_as_csv_stats_features__measure__csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: "count" | "length" | "area";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsFeaturesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0rc2+45857f1
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     timestamp;result
                     *     2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_contributors_count_as_json_stats_contributors_count_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsContributorsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsContributorsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_contributors_count_as_csv_stats_contributors_count_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsContributorsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0rc2+45857f1
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     start;end;value
                     *     2007-10-08T00:00:00Z;2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_contributors_count_as_json_stats_contributions_count_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsContributionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsContributionsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_contributors_count_as_csv_stats_contributions_count_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsContributionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0rc2+45857f1
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     start;end;value
                     *     2007-10-08T00:00:00Z;2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_currentness_as_json_stats_currentness__measure__json_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: "count" | "length" | "area";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsCurrentnessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsCurrentnessResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_currentness_as_csv_stats_currentness__measure__csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure: "count" | "length" | "area";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatsCurrentnessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # apiVersion: 2.0.0rc2+45857f1
                     *     # attribution.url: https://ohsome.org/copyrights
                     *     # attribution.text: © OpenStreetMap contributors
                     *     start;end;value
                     *     2007-10-08T00:00:00Z;2026-01-01T00:00:00Z;163
                     */
                    "text/csv": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_features_extract_extraction_features_parquet_get: {
        parameters: {
            query: {
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html). */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description xmin, ymin, xmax, ymax */
                aoi: string;
                time: string | "latest";
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_features_extract_extraction_features_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionFeaturesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_features_collections_extract_extraction_collections_parquet_get: {
        parameters: {
            query: {
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter). */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description xmin, ymin, xmax, ymax */
                aoi: string;
                time: string | "latest";
                /** @description Specific ohsome filter for members. */
                member_filter?: components["schemas"]["OhsomeFilter"] | null;
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_features_collections_extract_extraction_collections_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionCollectionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_features_collections_members_extract_extraction_collections_members_parquet_get: {
        parameters: {
            query: {
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#filter). */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description xmin, ymin, xmax, ymax */
                aoi: string;
                time: string | "latest";
                /** @description Specific ohsome filter for members. */
                member_filter?: components["schemas"]["OhsomeFilter"] | null;
                /** @description Whether to clip extracted features with AOI or not. */
                clip?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_features_collections_members_extract_extraction_collections_members_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionCollectionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_contributions_extract_extraction_contributions_parquet_get: {
        parameters: {
            query: {
                /** @description Filter for OSM data. Please refer to the [ohsome filter language documentation](https://docs.ohsome.org/ohsome-api/staging/reference/filter.html). */
                filter: components["schemas"]["OhsomeFilter"];
                /** @description xmin, ymin, xmax, ymax */
                aoi: string;
                /** @description Time range defined using a start/end timestamp (ISO-8601, UTC). Please take a look at the [documentation](https://docs.ohsome.org/ohsome-api/staging/reference.html#time). */
                time: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    post_contributions_extract_extraction_contributions_parquet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionContributionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
}
